[workspace]
members = [ "crates/context_sdk" ]

# Use the V2 resolver so that features and dependencies are handled consistently
resolver = "2"

[workspace.dependencies]
phase_space_sdk = { version = "0.1.0", path = "crates/context_sdk" }
